services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./test.db:/code/test.db
    environment:
      - SECRET_KEY=a_super_secret_key_for_docker
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

